services:
  ttyd:
    image: tsl0922/ttyd
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    #ports:
    #  - "17681:7681"
    #volumes:
    #  - ~/git:/mnt/git:ro
    #  - ~/aia1:/mnt/aia1
    #command: bash
    networks:
      - ai-agent-lab

networks:
  ai-agent-lab:
    external: true
    name: ai-agent-lab
