services:

  devbox:
    image: devbox:latest
    container_name: devbox
    build:
      context: ../../
      dockerfile: svcs/devbox/Dockerfile.devbox
      args:
        - USER=${USER:-devbox}
        - UID=${UID:-1001}
        - GID=${GID:-1001}
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    networks:
      - dind-lab
    environment:
      # Playwright Test will connect to the remote browser server
      - PW_TEST_CONNECT_WS_ENDPOINT=ws://pw:3000/

networks:
  dind-lab:
    external: true
    name: dind-lab
