services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    #ports:
    #  - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPEN_WEBUI_BASE_URL=/openwebui/
      #- WEBUI_URL=/openwebui/
      - WEBUI_URL=https://thinkpaddy.local/openwebui/
      - WEBUI_BASE_URL=https://thinkpaddy.local/openwebui/
      - "CORS_ALLOW_ORIGIN=https://thinkpaddy.local;https://open-webui:8080;http://open-webui:8080"
      - ENABLE_SIGNUP=true
      - ENABLE_LOGIN_FORM=true
    networks:
      - ai-agent-lab

volumes:
  open-webui:

networks:
  ai-agent-lab:
    external: true
    name: ai-agent-lab
