services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.58.2-noble
    container_name: ${DOCKER_CONTAINER_NAME}
    user: pwuser
    init: true
    ipc: host
    shm_size: "2gb"
    networks:
      - ai-agent-lab
    command: >
      /bin/sh -lc "npx -y playwright@1.58.2 run-server --port 3000 --host 0.0.0.0"

networks:
  ai-agent-lab:
    external: true
    name: ai-agent-lab
