services:
  vscode:
    image: linuxserver/code-server
    container_name: vscode
    restart: unless-stopped
    ports:
      - "11843:8443"
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
      - PASSWORD=password
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ./config:/config
    networks:
      - ai-agent-lab

networks:
  ai-agent-lab:
    external: true
