install:
	sudo cp -f com.user.caffeinate.plist /Library/LaunchDaemons/
	sudo chown root:wheel /Library/LaunchDaemons/com.user.caffeinate.plist
	sudo chmod 644 /Library/LaunchDaemons/com.user.caffeinate.plist
