services:
  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    privileged: true
    devices:
      - /dev/kvm
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    networks:
      - dind-lab
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    volumes:
      - android-data:/home/androidusr
    shm_size: "2gb"

networks:
  dind-lab:
    external: true
    name: dind-lab

volumes:
  android-data:
