services:
  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: ${DOCKER_CONTAINER_NAME}

    privileged: true
    devices:
      - /dev/kvm
    environment:
      - "EMULATOR_DEVICE=Samsung Galaxy S10"
      - "WEB_VNC=true"
    networks:
      - ai-agent-lab
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    volumes:
      - android-data:/home/androidusr
    shm_size: "2gb"

networks:
  ai-agent-lab:
    external: true
    name: ai-agent-lab

volumes:
  android-data:
