name: Run tests on app changes

on:
  push:
    paths:
      - 'bin/**'
      - 'apps/**'
  pull_request:
    paths:
      - 'bin/**'
      - 'apps/**'

jobs:

  make-test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Run tests
        run: make test
